ci: true
branches: ['master', 'main']

plugins:
  - - '@semantic-release/npm'
    - npmPublish: false
  - - '@semantic-release/git'
    - message: 'RELEASE: ${nextRelease.version}'
  - - '@semantic-release/changelog'
  - - '@semantic-release/gitlab'
  - - '@semantic-release/release-notes-generator'
    - presetConfig:
        types:
          - type: refactor
            section: Refactoring
          - type: style
            section: Refactoring
          - type: perf
            section: Refactoring
          - type: chore
            section: Refactoring
  - - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:
      - type: build
        release: patch
      - type: ci
        release: patch
      - type: refactor
        release: patch
      - type: chore
        release: patch
