version: "3.7"
services:
  app:
    image: ${REGISTRY}schedule-status-bot:${version:-latest}
    build:
      context: ../
      target: app
      dockerfile: deployment/Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.apps == true
          - node.labels.${ENV_NAME} == true
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    # ports:
    #   - ${APP_PORT:-7111}:8000
    env_file:
      - ../${ENV_NAME}.env
    environment:
      - BUILD_NUMBER=${BUILD_NUMBER}
      - PORT=8000
      - HOST=0.0.0.0
      - DOCKER_NODE={{.Node.Hostname}}
      - DOCKER_INSTANCE={{.Task.Slot}}
    networks:
      codabra:
        aliases:
          - schedule-status-bot
    restart: unless-stopped

networks:
  codabra:
    external: true
    name: ${ENV_NAME}_codabra
